### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn-schema#82]
Why is datetime_of_notice in the Alert.schema.json not consistent with the other parameters naming here:
"alert_tense" "alert_type".
Should be "alert_datetime" (as it used to be!)

**Comment by Tohuvavohu** [comment]
Also i'll note that i was able to commit even with this outdated field name because the validator doesn't work (re https://github.com/nasa-gcn/gcn-schema/issues/80)

**Comment by dakota002** [comment]
@Tohuvavohu in your schema I see you are using the anyOf keyword. anyOf will validate as true if at least one of the referenced schemas are valid. I would recommend that you try replacing it with allOf if you are trying to ensure that all of the referenced schema validate. You can use a combination of the `anyOf`, `allOf`, `oneOf`, and `properies`  keywords to define the structure with more granularity

**Comment by joshuarwood** [comment]
@dakota002 I don't think it's appropriate to recommend using allOf. Not all alert schema will inherit all of the core fields from each subschema. There should be a way to validate a subschema with anyOf. jsonschema has this functionality.

**Comment by joshuarwood** [comment]
A case example is the localization schema. There is no need to include a healpix_url if a b64 encoded healpix_file is included. Circular error definitions don't need both ra_uncertainty/dec_uncertainty/position angle/etc.
https://github.com/nasa-gcn/gcn-schema/blob/main/gcn/notices/core/Localization.schema.json

**Comment by dakota002** [comment]
@joshuarwood the allOf only applies to the validation on the level of the specified schema. This does not make all of the properties recursively required, only that they are each valid. Since most of them don't have any required properties, they would still be valid even if you omit fields. So in the case here we would probably still run into the false positive.

This test results in the expected result, using your example from #80 
![image](https://github.com/nasa-gcn/gcn-schema/assets/11023698/0de1ed6e-a863-4ab6-b9bf-207f6939f3f9)


I think you make a good point though regarding the conditionality of some fields. Json schema does support [conditionally defining](https://json-schema.org/understanding-json-schema/reference/conditionals.html) properties. We can definitely look deeper into applying some more conditional logic in some later updates

**Comment by Tohuvavohu** [comment]
Dakota, thanks for your thoughts here.
 I will note however that the validator still doesn't work even with using 'allOf' because it still successfully validates on a property type that does not exist in the schema ("alert_datetime").
See current version of PR: https://github.com/nasa-gcn/gcn-schema/pull/79
Am i  missing something here?

@lpsinger @jracusin

**Comment by dakota002** [comment]
@Tohuvavohu I see what you're saying there. I think then what we really need to implement on some level is setting additionalProperties to false. This should effectively cause the validation to fail when properties are added that dont belong to the overall structure. Can you try adding `"additionalProperties" :false` ,without changing anything else, to your alert schema and see if it throws an error as expected? 
This would technically catch any typos or name changes, here is an example i tried locally:
![image](https://github.com/nasa-gcn/gcn-schema/assets/11023698/955f355f-0ba4-4c53-9be9-0f354ccd2c69)

**Comment by dakota002** [comment]
But i will add that keeping the naming consistent is probably a good idea, it should probably follow the alert_* pattern

**Comment by Tohuvavohu** [comment]
Dakota @lpsinger @jracusin 
Your suggestion breaks your own validator.
It does indeed throw "must not HAVE additional properties", as in your screenshot, when setting
additionalProperties:false,
 BUT this is not because my/your example uses properties not in the schema....but because it doesn't like the $schema property itself.

Your validator is broken, and there is no way for us to confidently develop on this repo until it is fixed.

**Comment by lpsinger** [comment]
@Tohuvavohu, do you have a branch with a schema that you think should validate, but does not? If so, would you please open a separate PR with that failing test case? Then we will work with you to fix it and get it merged.

Meanwhile, the topic of this issue appears to be the inconsistent naming of the `datetime_of_notice` field. I agree that's inconsistent! @dakota002, could we please fix that so that we can close this issue?

**Comment by Tohuvavohu** [comment]
I've fixed the inconsistenty in the PR #79 .

**Comment by Tohuvavohu** [comment]
re the validator.
The problem is that in order to make the validator *actually check* that the example notices don't have properties not in the schema (or typos, namechanges,etc), @dakota002 pointed out that you have to include
`additionalProperties:false`
however, then validation fails because it doesn't like the $schema property in the example notices.
In order to open a PR with this, i will have to bypass the pre-commit hooks.
Will do so.

**Comment by dakota002** [comment]
What errors were you getting with the validator for the $schema properties?

**Comment by Tohuvavohu** [comment]
"must NOT have additional properties"!

**Comment by dakota002** [comment]
Ah I see, I was able to get that locally too

**Comment by dakota002** [comment]
I have a solution in mind, I will get a PR out shortly

**Comment by lpsinger** [comment]
Folks, please, let's keep issues on topic. Let's carry on the `anyOf`/`allOf` discussion on #79.

Meanwhile, on the topic of _this_ issue, have we resolved the inconsistent naming issue?

**Comment by Tohuvavohu** [comment]
> Meanwhile, on the topic of this issue, have we resolved the inconsistent naming issue?
This is addressed by https://github.com/nasa-gcn/gcn-schema/pull/79

**Comment by lpsinger** [comment]
@Tohuvavohu, thank you. I pulled that change out separately as #83 because it affects several other schema.
